//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.09 at 09:56:29 PM BST 
//


package xades4j.xml.bind.xades;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xades4j.xml.bind.xades package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    public static final String ORG_01903_V_1_3_2 = "http://uri.etsi.org/01903/v1.3.2#";
    public static final String ORG_01903_V_1_4_1 = "http://uri.etsi.org/01903/v1.4.1#";
    private static final QName _UnsignedDataObjectProperties_QNAME = new QName(ORG_01903_V_1_3_2, "UnsignedDataObjectProperties");
    private static final QName _SignatureTimeStamp_QNAME = new QName(ORG_01903_V_1_3_2, "SignatureTimeStamp");
    private static final QName _IndividualDataObjectsTimeStamp_QNAME = new QName(ORG_01903_V_1_3_2, "IndividualDataObjectsTimeStamp");
    private static final QName _AttrAuthoritiesCertValues_QNAME = new QName(ORG_01903_V_1_3_2, "AttrAuthoritiesCertValues");
    private static final QName _ArchiveTimeStamp_QNAME = new QName(ORG_01903_V_1_3_2, "ArchiveTimeStamp");
    private static final QName _SPUserNotice_QNAME = new QName(ORG_01903_V_1_3_2, "SPUserNotice");
    private static final QName _UnsignedProperties_QNAME = new QName(ORG_01903_V_1_3_2, "UnsignedProperties");
    private static final QName _CompleteRevocationRefs_QNAME = new QName(ORG_01903_V_1_3_2, "CompleteRevocationRefs");
    private static final QName _AttributeRevocationValues_QNAME = new QName(ORG_01903_V_1_3_2, "AttributeRevocationValues");
    private static final QName _SignedSignatureProperties_QNAME = new QName(ORG_01903_V_1_3_2, "SignedSignatureProperties");
    private static final QName _ObjectIdentifier_QNAME = new QName(ORG_01903_V_1_3_2, "ObjectIdentifier");
    private static final QName _OtherTimeStamp_QNAME = new QName(ORG_01903_V_1_3_2, "OtherTimeStamp");
    private static final QName _RefsOnlyTimeStamp_QNAME = new QName(ORG_01903_V_1_3_2, "RefsOnlyTimeStamp");
    private static final QName _SPURI_QNAME = new QName(ORG_01903_V_1_3_2, "SPURI");
    private static final QName _SignedDataObjectProperties_QNAME = new QName(ORG_01903_V_1_3_2, "SignedDataObjectProperties");
    private static final QName _CounterSignature_QNAME = new QName(ORG_01903_V_1_3_2, "CounterSignature");
    private static final QName _QualifyingProperties_QNAME = new QName(ORG_01903_V_1_3_2, "QualifyingProperties");
    private static final QName _SigningCertificate_QNAME = new QName(ORG_01903_V_1_3_2, "SigningCertificate");
    private static final QName _ReferenceInfo_QNAME = new QName(ORG_01903_V_1_3_2, "ReferenceInfo");
    private static final QName _XAdESTimeStamp_QNAME = new QName(ORG_01903_V_1_3_2, "XAdESTimeStamp");
    private static final QName _SignatureProductionPlace_QNAME = new QName(ORG_01903_V_1_3_2, "SignatureProductionPlace");
    private static final QName _EncapsulatedPKIData_QNAME = new QName(ORG_01903_V_1_3_2, "EncapsulatedPKIData");
    private static final QName _UnsignedSignatureProperties_QNAME = new QName(ORG_01903_V_1_3_2, "UnsignedSignatureProperties");
    private static final QName _CommitmentTypeIndication_QNAME = new QName(ORG_01903_V_1_3_2, "CommitmentTypeIndication");
    private static final QName _AllDataObjectsTimeStamp_QNAME = new QName(ORG_01903_V_1_3_2, "AllDataObjectsTimeStamp");
    private static final QName _SignerRole_QNAME = new QName(ORG_01903_V_1_3_2, "SignerRole");
    private static final QName _RevocationValues_QNAME = new QName(ORG_01903_V_1_3_2, "RevocationValues");
    private static final QName _ArchiveTimeStampV2_QNAME = new QName(ORG_01903_V_1_4_1, "ArchiveTimeStampV2");
    private static final QName _QualifyingPropertiesReference_QNAME = new QName(ORG_01903_V_1_3_2, "QualifyingPropertiesReference");
    private static final QName _CertificateValues_QNAME = new QName(ORG_01903_V_1_3_2, "CertificateValues");
    private static final QName _Any_QNAME = new QName(ORG_01903_V_1_3_2, "Any");
    private static final QName _SignaturePolicyIdentifier_QNAME = new QName(ORG_01903_V_1_3_2, "SignaturePolicyIdentifier");
    private static final QName _SigningTime_QNAME = new QName(ORG_01903_V_1_3_2, "SigningTime");
    private static final QName _Include_QNAME = new QName(ORG_01903_V_1_3_2, "Include");
    private static final QName _SigAndRefsTimeStamp_QNAME = new QName(ORG_01903_V_1_3_2, "SigAndRefsTimeStamp");
    private static final QName _DataObjectFormat_QNAME = new QName(ORG_01903_V_1_3_2, "DataObjectFormat");
    private static final QName _AttributeCertificateRefs_QNAME = new QName(ORG_01903_V_1_3_2, "AttributeCertificateRefs");
    private static final QName _TimeStampValidationData_QNAME = new QName("ORG_01903_V_1_4_1", "TimeStampValidationData");
    private static final QName _SignedProperties_QNAME = new QName(ORG_01903_V_1_3_2, "SignedProperties");
    private static final QName _CompleteCertificateRefs_QNAME = new QName(ORG_01903_V_1_3_2, "CompleteCertificateRefs");
    private static final QName _AttributeRevocationRefs_QNAME = new QName(ORG_01903_V_1_3_2, "AttributeRevocationRefs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xades4j.marshalling.xades
     *
     */
    public ObjectFactory() {
        // TODO document why this constructor is empty
    }

    /**
     * Create an instance of {@link XmlCertifiedRolesListType }
     *
     */
    public XmlCertifiedRolesListType createXmlCertifiedRolesListType() {
        return new XmlCertifiedRolesListType();
    }

    /**
     * Create an instance of {@link XmlCommitmentTypeIndicationType }
     *
     */
    public XmlCommitmentTypeIndicationType createXmlCommitmentTypeIndicationType() {
        return new XmlCommitmentTypeIndicationType();
    }

    /**
     * Create an instance of {@link XmlRevocationValuesType }
     *
     */
    public XmlRevocationValuesType createXmlRevocationValuesType() {
        return new XmlRevocationValuesType();
    }

    /**
     * Create an instance of {@link XmlDocumentationReferencesType }
     *
     */
    public XmlDocumentationReferencesType createXmlDocumentationReferencesType() {
        return new XmlDocumentationReferencesType();
    }

    /**
     * Create an instance of {@link XmlSPUserNoticeType }
     *
     */
    public XmlSPUserNoticeType createXmlSPUserNoticeType() {
        return new XmlSPUserNoticeType();
    }

    /**
     * Create an instance of {@link XmlCertIDListType }
     *
     */
    public XmlCertIDListType createXmlCertIDListType() {
        return new XmlCertIDListType();
    }

    /**
     * Create an instance of {@link XmlSignedPropertiesType }
     *
     */
    public XmlSignedPropertiesType createXmlSignedPropertiesType() {
        return new XmlSignedPropertiesType();
    }

    /**
     * Create an instance of {@link XmlSignaturePolicyIdType }
     *
     */
    public XmlSignaturePolicyIdType createXmlSignaturePolicyIdType() {
        return new XmlSignaturePolicyIdType();
    }

    /**
     * Create an instance of {@link XmlReferenceInfoType }
     *
     */
    public XmlReferenceInfoType createXmlReferenceInfoType() {
        return new XmlReferenceInfoType();
    }

    /**
     * Create an instance of {@link XmlOCSPRefsType }
     *
     */
    public XmlOCSPRefsType createXmlOCSPRefsType() {
        return new XmlOCSPRefsType();
    }

    /**
     * Create an instance of {@link XmlEncapsulatedPKIDataType }
     *
     */
    public XmlEncapsulatedPKIDataType createXmlEncapsulatedPKIDataType() {
        return new XmlEncapsulatedPKIDataType();
    }

    /**
     * Create an instance of {@link XmlCompleteCertificateRefsType }
     *
     */
    public XmlCompleteCertificateRefsType createXmlCompleteCertificateRefsType() {
        return new XmlCompleteCertificateRefsType();
    }

    /**
     * Create an instance of {@link XmlDigestAlgAndValueType }
     *
     */
    public XmlDigestAlgAndValueType createXmlDigestAlgAndValueType() {
        return new XmlDigestAlgAndValueType();
    }

    /**
     * Create an instance of {@link XmlObjectIdentifierType }
     *
     */
    public XmlObjectIdentifierType createXmlObjectIdentifierType() {
        return new XmlObjectIdentifierType();
    }

    /**
     * Create an instance of {@link XmlOCSPRefType }
     *
     */
    public XmlOCSPRefType createXmlOCSPRefType() {
        return new XmlOCSPRefType();
    }

    /**
     * Create an instance of {@link XmlCRLRefType }
     *
     */
    public XmlCRLRefType createXmlCRLRefType() {
        return new XmlCRLRefType();
    }

    /**
     * Create an instance of {@link XmlUnsignedSignaturePropertiesType }
     *
     */
    public XmlUnsignedSignaturePropertiesType createXmlUnsignedSignaturePropertiesType() {
        return new XmlUnsignedSignaturePropertiesType();
    }

    /**
     * Create an instance of {@link XmlSignerRoleType }
     *
     */
    public XmlSignerRoleType createXmlSignerRoleType() {
        return new XmlSignerRoleType();
    }

    /**
     * Create an instance of {@link XmlUnsignedDataObjectPropertiesType }
     *
     */
    public XmlUnsignedDataObjectPropertiesType createXmlUnsignedDataObjectPropertiesType() {
        return new XmlUnsignedDataObjectPropertiesType();
    }

    /**
     * Create an instance of {@link XmlIdentifierType }
     *
     */
    public XmlIdentifierType createXmlIdentifierType() {
        return new XmlIdentifierType();
    }

    /**
     * Create an instance of {@link XmlCounterSignatureType }
     *
     */
    public XmlCounterSignatureType createXmlCounterSignatureType() {
        return new XmlCounterSignatureType();
    }

    /**
     * Create an instance of {@link XmlSignedDataObjectPropertiesType }
     *
     */
    public XmlSignedDataObjectPropertiesType createXmlSignedDataObjectPropertiesType() {
        return new XmlSignedDataObjectPropertiesType();
    }

    /**
     * Create an instance of {@link XmlUnsignedPropertiesType }
     *
     */
    public XmlUnsignedPropertiesType createXmlUnsignedPropertiesType() {
        return new XmlUnsignedPropertiesType();
    }

    /**
     * Create an instance of {@link XmlNoticeReferenceType }
     *
     */
    public XmlNoticeReferenceType createXmlNoticeReferenceType() {
        return new XmlNoticeReferenceType();
    }

    /**
     * Create an instance of {@link XmlCertificateValuesType }
     *
     */
    public XmlCertificateValuesType createXmlCertificateValuesType() {
        return new XmlCertificateValuesType();
    }

    /**
     * Create an instance of {@link XmlOtherCertStatusRefsType }
     *
     */
    public XmlOtherCertStatusRefsType createXmlOtherCertStatusRefsType() {
        return new XmlOtherCertStatusRefsType();
    }

    /**
     * Create an instance of {@link XmlQualifyingPropertiesType }
     *
     */
    public XmlQualifyingPropertiesType createXmlQualifyingPropertiesType() {
        return new XmlQualifyingPropertiesType();
    }

    /**
     * Create an instance of {@link XmlCommitmentTypeQualifiersListType }
     *
     */
    public XmlCommitmentTypeQualifiersListType createXmlCommitmentTypeQualifiersListType() {
        return new XmlCommitmentTypeQualifiersListType();
    }

    /**
     * Create an instance of {@link XmlSignatureProductionPlaceType }
     *
     */
    public XmlSignatureProductionPlaceType createXmlSignatureProductionPlaceType() {
        return new XmlSignatureProductionPlaceType();
    }

    /**
     * Create an instance of {@link XmlSignedSignaturePropertiesType }
     *
     */
    public XmlSignedSignaturePropertiesType createXmlSignedSignaturePropertiesType() {
        return new XmlSignedSignaturePropertiesType();
    }

    /**
     * Create an instance of {@link XmlOtherTimeStampType }
     *
     */
    public XmlOtherTimeStampType createXmlOtherTimeStampType() {
        return new XmlOtherTimeStampType();
    }

    /**
     * Create an instance of {@link XmlCRLValuesType }
     *
     */
    public XmlCRLValuesType createXmlCRLValuesType() {
        return new XmlCRLValuesType();
    }

    /**
     * Create an instance of {@link XmlXAdESTimeStampType }
     *
     */
    public XmlXAdESTimeStampType createXmlXAdESTimeStampType() {
        return new XmlXAdESTimeStampType();
    }

    /**
     * Create an instance of {@link XmlSigPolicyQualifiersListType }
     *
     */
    public XmlSigPolicyQualifiersListType createXmlSigPolicyQualifiersListType() {
        return new XmlSigPolicyQualifiersListType();
    }

    /**
     * Create an instance of {@link XmlCompleteRevocationRefsType }
     *
     */
    public XmlCompleteRevocationRefsType createXmlCompleteRevocationRefsType() {
        return new XmlCompleteRevocationRefsType();
    }

    /**
     * Create an instance of {@link XmlOCSPValuesType }
     *
     */
    public XmlOCSPValuesType createXmlOCSPValuesType() {
        return new XmlOCSPValuesType();
    }

    /**
     * Create an instance of {@link XmlCRLIdentifierType }
     *
     */
    public XmlCRLIdentifierType createXmlCRLIdentifierType() {
        return new XmlCRLIdentifierType();
    }

    /**
     * Create an instance of {@link XmlClaimedRolesListType }
     *
     */
    public XmlClaimedRolesListType createXmlClaimedRolesListType() {
        return new XmlClaimedRolesListType();
    }

    /**
     * Create an instance of {@link XmlResponderIDType }
     *
     */
    public XmlResponderIDType createXmlResponderIDType() {
        return new XmlResponderIDType();
    }

    /**
     * Create an instance of {@link XmlQualifyingPropertiesReferenceType }
     *
     */
    public XmlQualifyingPropertiesReferenceType createXmlQualifyingPropertiesReferenceType() {
        return new XmlQualifyingPropertiesReferenceType();
    }

    /**
     * Create an instance of {@link XmlOtherCertStatusValuesType }
     *
     */
    public XmlOtherCertStatusValuesType createXmlOtherCertStatusValuesType() {
        return new XmlOtherCertStatusValuesType();
    }

    /**
     * Create an instance of {@link XmlIncludeType }
     *
     */
    public XmlIncludeType createXmlIncludeType() {
        return new XmlIncludeType();
    }

    /**
     * Create an instance of {@link XmlCRLRefsType }
     *
     */
    public XmlCRLRefsType createXmlCRLRefsType() {
        return new XmlCRLRefsType();
    }

    /**
     * Create an instance of {@link XmlAnyType }
     *
     */
    public XmlAnyType createXmlAnyType() {
        return new XmlAnyType();
    }

    /**
     * Create an instance of {@link XmlSignaturePolicyIdentifierType }
     *
     */
    public XmlSignaturePolicyIdentifierType createXmlSignaturePolicyIdentifierType() {
        return new XmlSignaturePolicyIdentifierType();
    }

    /**
     * Create an instance of {@link XmlCertIDType }
     *
     */
    public XmlCertIDType createXmlCertIDType() {
        return new XmlCertIDType();
    }

    /**
     * Create an instance of {@link XmlIntegerListType }
     *
     */
    public XmlIntegerListType createXmlIntegerListType() {
        return new XmlIntegerListType();
    }

    /**
     * Create an instance of {@link XmlOCSPIdentifierType }
     *
     */
    public XmlOCSPIdentifierType createXmlOCSPIdentifierType() {
        return new XmlOCSPIdentifierType();
    }

    /**
     * Create an instance of {@link XmlDataObjectFormatType }
     *
     */
    public XmlDataObjectFormatType createXmlDataObjectFormatType() {
        return new XmlDataObjectFormatType();
    }

    /**
     * Create an instance of {@link XmlValidationDataType }
     *
     */
    public XmlValidationDataType createXmlValidationDataType() {
        return new XmlValidationDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlUnsignedDataObjectPropertiesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "UnsignedDataObjectProperties")
    public JAXBElement<XmlUnsignedDataObjectPropertiesType> createUnsignedDataObjectProperties(XmlUnsignedDataObjectPropertiesType value) {
        return new JAXBElement<>(_UnsignedDataObjectProperties_QNAME, XmlUnsignedDataObjectPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SignatureTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createSignatureTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_SignatureTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "IndividualDataObjectsTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createIndividualDataObjectsTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_IndividualDataObjectsTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCertificateValuesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "AttrAuthoritiesCertValues")
    public JAXBElement<XmlCertificateValuesType> createAttrAuthoritiesCertValues(XmlCertificateValuesType value) {
        return new JAXBElement<>(_AttrAuthoritiesCertValues_QNAME, XmlCertificateValuesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "ArchiveTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createArchiveTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_ArchiveTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSPUserNoticeType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SPUserNotice")
    public JAXBElement<XmlSPUserNoticeType> createSPUserNotice(XmlSPUserNoticeType value) {
        return new JAXBElement<>(_SPUserNotice_QNAME, XmlSPUserNoticeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlUnsignedPropertiesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "UnsignedProperties")
    public JAXBElement<XmlUnsignedPropertiesType> createUnsignedProperties(XmlUnsignedPropertiesType value) {
        return new JAXBElement<>(_UnsignedProperties_QNAME, XmlUnsignedPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteRevocationRefsType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "CompleteRevocationRefs")
    public JAXBElement<XmlCompleteRevocationRefsType> createCompleteRevocationRefs(XmlCompleteRevocationRefsType value) {
        return new JAXBElement<>(_CompleteRevocationRefs_QNAME, XmlCompleteRevocationRefsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlRevocationValuesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "AttributeRevocationValues")
    public JAXBElement<XmlRevocationValuesType> createAttributeRevocationValues(XmlRevocationValuesType value) {
        return new JAXBElement<>(_AttributeRevocationValues_QNAME, XmlRevocationValuesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignedSignaturePropertiesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SignedSignatureProperties")
    public JAXBElement<XmlSignedSignaturePropertiesType> createSignedSignatureProperties(XmlSignedSignaturePropertiesType value) {
        return new JAXBElement<>(_SignedSignatureProperties_QNAME, XmlSignedSignaturePropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlObjectIdentifierType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "ObjectIdentifier")
    public JAXBElement<XmlObjectIdentifierType> createObjectIdentifier(XmlObjectIdentifierType value) {
        return new JAXBElement<>(_ObjectIdentifier_QNAME, XmlObjectIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlOtherTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "OtherTimeStamp")
    public JAXBElement<XmlOtherTimeStampType> createOtherTimeStamp(XmlOtherTimeStampType value) {
        return new JAXBElement<>(_OtherTimeStamp_QNAME, XmlOtherTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "RefsOnlyTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createRefsOnlyTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_RefsOnlyTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SPURI")
    public JAXBElement<String> createSPURI(String value) {
        return new JAXBElement<>(_SPURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignedDataObjectPropertiesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SignedDataObjectProperties")
    public JAXBElement<XmlSignedDataObjectPropertiesType> createSignedDataObjectProperties(XmlSignedDataObjectPropertiesType value) {
        return new JAXBElement<>(_SignedDataObjectProperties_QNAME, XmlSignedDataObjectPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCounterSignatureType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "CounterSignature")
    public JAXBElement<XmlCounterSignatureType> createCounterSignature(XmlCounterSignatureType value) {
        return new JAXBElement<>(_CounterSignature_QNAME, XmlCounterSignatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlQualifyingPropertiesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "QualifyingProperties")
    public JAXBElement<XmlQualifyingPropertiesType> createQualifyingProperties(XmlQualifyingPropertiesType value) {
        return new JAXBElement<>(_QualifyingProperties_QNAME, XmlQualifyingPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCertIDListType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SigningCertificate")
    public JAXBElement<XmlCertIDListType> createSigningCertificate(XmlCertIDListType value) {
        return new JAXBElement<>(_SigningCertificate_QNAME, XmlCertIDListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlReferenceInfoType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "ReferenceInfo")
    public JAXBElement<XmlReferenceInfoType> createReferenceInfo(XmlReferenceInfoType value) {
        return new JAXBElement<>(_ReferenceInfo_QNAME, XmlReferenceInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "XAdESTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createXAdESTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_XAdESTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignatureProductionPlaceType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SignatureProductionPlace")
    public JAXBElement<XmlSignatureProductionPlaceType> createSignatureProductionPlace(XmlSignatureProductionPlaceType value) {
        return new JAXBElement<>(_SignatureProductionPlace_QNAME, XmlSignatureProductionPlaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlEncapsulatedPKIDataType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "EncapsulatedPKIData")
    public JAXBElement<XmlEncapsulatedPKIDataType> createEncapsulatedPKIData(XmlEncapsulatedPKIDataType value) {
        return new JAXBElement<>(_EncapsulatedPKIData_QNAME, XmlEncapsulatedPKIDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlUnsignedSignaturePropertiesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "UnsignedSignatureProperties")
    public JAXBElement<XmlUnsignedSignaturePropertiesType> createUnsignedSignatureProperties(XmlUnsignedSignaturePropertiesType value) {
        return new JAXBElement<>(_UnsignedSignatureProperties_QNAME, XmlUnsignedSignaturePropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCommitmentTypeIndicationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "CommitmentTypeIndication")
    public JAXBElement<XmlCommitmentTypeIndicationType> createCommitmentTypeIndication(XmlCommitmentTypeIndicationType value) {
        return new JAXBElement<>(_CommitmentTypeIndication_QNAME, XmlCommitmentTypeIndicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "AllDataObjectsTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createAllDataObjectsTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_AllDataObjectsTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignerRoleType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SignerRole")
    public JAXBElement<XmlSignerRoleType> createSignerRole(XmlSignerRoleType value) {
        return new JAXBElement<>(_SignerRole_QNAME, XmlSignerRoleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlRevocationValuesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "RevocationValues")
    public JAXBElement<XmlRevocationValuesType> createRevocationValues(XmlRevocationValuesType value) {
        return new JAXBElement<>(_RevocationValues_QNAME, XmlRevocationValuesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "ArchiveTimeStampV2")
    public JAXBElement<XmlXAdESTimeStampType> createArchiveTimeStampV2(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_ArchiveTimeStampV2_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlQualifyingPropertiesReferenceType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "QualifyingPropertiesReference")
    public JAXBElement<XmlQualifyingPropertiesReferenceType> createQualifyingPropertiesReference(XmlQualifyingPropertiesReferenceType value) {
        return new JAXBElement<>(_QualifyingPropertiesReference_QNAME, XmlQualifyingPropertiesReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCertificateValuesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "CertificateValues")
    public JAXBElement<XmlCertificateValuesType> createCertificateValues(XmlCertificateValuesType value) {
        return new JAXBElement<>(_CertificateValues_QNAME, XmlCertificateValuesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlAnyType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "Any")
    public JAXBElement<XmlAnyType> createAny(XmlAnyType value) {
        return new JAXBElement<>(_Any_QNAME, XmlAnyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignaturePolicyIdentifierType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SignaturePolicyIdentifier")
    public JAXBElement<XmlSignaturePolicyIdentifierType> createSignaturePolicyIdentifier(XmlSignaturePolicyIdentifierType value) {
        return new JAXBElement<>(_SignaturePolicyIdentifier_QNAME, XmlSignaturePolicyIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SigningTime")
    public JAXBElement<XMLGregorianCalendar> createSigningTime(XMLGregorianCalendar value) {
        return new JAXBElement<>(_SigningTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlIncludeType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "Include")
    public JAXBElement<XmlIncludeType> createInclude(XmlIncludeType value) {
        return new JAXBElement<>(_Include_QNAME, XmlIncludeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SigAndRefsTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createSigAndRefsTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_SigAndRefsTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlDataObjectFormatType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "DataObjectFormat")
    public JAXBElement<XmlDataObjectFormatType> createDataObjectFormat(XmlDataObjectFormatType value) {
        return new JAXBElement<>(_DataObjectFormat_QNAME, XmlDataObjectFormatType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteCertificateRefsType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "AttributeCertificateRefs")
    public JAXBElement<XmlCompleteCertificateRefsType> createAttributeCertificateRefs(XmlCompleteCertificateRefsType value) {
        return new JAXBElement<>(_AttributeCertificateRefs_QNAME, XmlCompleteCertificateRefsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlValidationDataType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "TimeStampValidationData")
    public JAXBElement<XmlValidationDataType> createTimeStampValidationData(XmlValidationDataType value) {
        return new JAXBElement<>(_TimeStampValidationData_QNAME, XmlValidationDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignedPropertiesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SignedProperties")
    public JAXBElement<XmlSignedPropertiesType> createSignedProperties(XmlSignedPropertiesType value) {
        return new JAXBElement<>(_SignedProperties_QNAME, XmlSignedPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteCertificateRefsType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "CompleteCertificateRefs")
    public JAXBElement<XmlCompleteCertificateRefsType> createCompleteCertificateRefs(XmlCompleteCertificateRefsType value) {
        return new JAXBElement<>(_CompleteCertificateRefs_QNAME, XmlCompleteCertificateRefsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteRevocationRefsType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "AttributeRevocationRefs")
    public JAXBElement<XmlCompleteRevocationRefsType> createAttributeRevocationRefs(XmlCompleteRevocationRefsType value) {
        return new JAXBElement<>(_AttributeRevocationRefs_QNAME, XmlCompleteRevocationRefsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SignatureTimeStamp", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlXAdESTimeStampType> createXmlUnsignedSignaturePropertiesTypeSignatureTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_SignatureTimeStamp_QNAME, XmlXAdESTimeStampType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCertificateValuesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "CertificateValues", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlCertificateValuesType> createXmlUnsignedSignaturePropertiesTypeCertificateValues(XmlCertificateValuesType value) {
        return new JAXBElement<>(_CertificateValues_QNAME, XmlCertificateValuesType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "RefsOnlyTimeStamp", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlXAdESTimeStampType> createXmlUnsignedSignaturePropertiesTypeRefsOnlyTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_RefsOnlyTimeStamp_QNAME, XmlXAdESTimeStampType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCertificateValuesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "AttrAuthoritiesCertValues", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlCertificateValuesType> createXmlUnsignedSignaturePropertiesTypeAttrAuthoritiesCertValues(XmlCertificateValuesType value) {
        return new JAXBElement<>(_AttrAuthoritiesCertValues_QNAME, XmlCertificateValuesType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "ArchiveTimeStamp", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlXAdESTimeStampType> createXmlUnsignedSignaturePropertiesTypeArchiveTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_ArchiveTimeStamp_QNAME, XmlXAdESTimeStampType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "SigAndRefsTimeStamp", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlXAdESTimeStampType> createXmlUnsignedSignaturePropertiesTypeSigAndRefsTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<>(_SigAndRefsTimeStamp_QNAME, XmlXAdESTimeStampType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCounterSignatureType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "CounterSignature", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlCounterSignatureType> createXmlUnsignedSignaturePropertiesTypeCounterSignature(XmlCounterSignatureType value) {
        return new JAXBElement<>(_CounterSignature_QNAME, XmlCounterSignatureType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteRevocationRefsType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "CompleteRevocationRefs", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlCompleteRevocationRefsType> createXmlUnsignedSignaturePropertiesTypeCompleteRevocationRefs(XmlCompleteRevocationRefsType value) {
        return new JAXBElement<>(_CompleteRevocationRefs_QNAME, XmlCompleteRevocationRefsType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteCertificateRefsType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "AttributeCertificateRefs", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlCompleteCertificateRefsType> createXmlUnsignedSignaturePropertiesTypeAttributeCertificateRefs(XmlCompleteCertificateRefsType value) {
        return new JAXBElement<>(_AttributeCertificateRefs_QNAME, XmlCompleteCertificateRefsType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlRevocationValuesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "AttributeRevocationValues", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlRevocationValuesType> createXmlUnsignedSignaturePropertiesTypeAttributeRevocationValues(XmlRevocationValuesType value) {
        return new JAXBElement<>(_AttributeRevocationValues_QNAME, XmlRevocationValuesType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteCertificateRefsType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "CompleteCertificateRefs", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlCompleteCertificateRefsType> createXmlUnsignedSignaturePropertiesTypeCompleteCertificateRefs(XmlCompleteCertificateRefsType value) {
        return new JAXBElement<>(_CompleteCertificateRefs_QNAME, XmlCompleteCertificateRefsType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlRevocationValuesType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "RevocationValues", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlRevocationValuesType> createXmlUnsignedSignaturePropertiesTypeRevocationValues(XmlRevocationValuesType value) {
        return new JAXBElement<>(_RevocationValues_QNAME, XmlRevocationValuesType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteRevocationRefsType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = ORG_01903_V_1_3_2, name = "AttributeRevocationRefs", scope = XmlUnsignedSignaturePropertiesType.class)
    public JAXBElement<XmlCompleteRevocationRefsType> createXmlUnsignedSignaturePropertiesTypeAttributeRevocationRefs(XmlCompleteRevocationRefsType value) {
        return new JAXBElement<>(_AttributeRevocationRefs_QNAME, XmlCompleteRevocationRefsType.class, XmlUnsignedSignaturePropertiesType.class, value);
    }

}
