//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.04.13 at 11:16:20 AM BST
//
package xades4j.xml.bind.xades;

import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import xades4j.xml.bind.DateTimeXmlAdapter;

/**
 * <p>Java class for SignedSignaturePropertiesType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SignedSignaturePropertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SigningTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="SigningCertificate" type="{http://uri.etsi.org/01903/v1.3.2#}CertIDListType" minOccurs="0"/>
 *         &lt;element name="SignaturePolicyIdentifier" type="{http://uri.etsi.org/01903/v1.3.2#}SignaturePolicyIdentifierType" minOccurs="0"/>
 *         &lt;element name="SignatureProductionPlace" type="{http://uri.etsi.org/01903/v1.3.2#}SignatureProductionPlaceType" minOccurs="0"/>
 *         &lt;element name="SignerRole" type="{http://uri.etsi.org/01903/v1.3.2#}SignerRoleType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignedSignaturePropertiesType", propOrder =
{
    "signingTime",
    "signingCertificate",
    "signaturePolicyIdentifier",
    "signatureProductionPlace",
    "signerRole"
})
public class XmlSignedSignaturePropertiesType
{
    @XmlElement(name = "SigningTime", type = String.class)
    @XmlJavaTypeAdapter(DateTimeXmlAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar signingTime;
    @XmlElement(name = "SigningCertificate")
    protected XmlCertIDListType signingCertificate;
    @XmlElement(name = "SignaturePolicyIdentifier")
    protected XmlSignaturePolicyIdentifierType signaturePolicyIdentifier;
    @XmlElement(name = "SignatureProductionPlace")
    protected XmlSignatureProductionPlaceType signatureProductionPlace;
    @XmlElement(name = "SignerRole")
    protected XmlSignerRoleType signerRole;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the signingTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public Calendar getSigningTime()
    {
        return signingTime;
    }

    /**
     * Sets the value of the signingTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSigningTime(Calendar value)
    {
        this.signingTime = value;
    }

    /**
     * Gets the value of the signingCertificate property.
     *
     * @return
     *     possible object is
     *     {@link XmlCertIDListType }
     *
     */
    public XmlCertIDListType getSigningCertificate()
    {
        return signingCertificate;
    }

    /**
     * Sets the value of the signingCertificate property.
     *
     * @param value
     *     allowed object is
     *     {@link XmlCertIDListType }
     *
     */
    public void setSigningCertificate(XmlCertIDListType value)
    {
        this.signingCertificate = value;
    }

    /**
     * Gets the value of the signaturePolicyIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link XmlSignaturePolicyIdentifierType }
     *
     */
    public XmlSignaturePolicyIdentifierType getSignaturePolicyIdentifier()
    {
        return signaturePolicyIdentifier;
    }

    /**
     * Sets the value of the signaturePolicyIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link XmlSignaturePolicyIdentifierType }
     *
     */
    public void setSignaturePolicyIdentifier(
            XmlSignaturePolicyIdentifierType value)
    {
        this.signaturePolicyIdentifier = value;
    }

    /**
     * Gets the value of the signatureProductionPlace property.
     *
     * @return
     *     possible object is
     *     {@link XmlSignatureProductionPlaceType }
     *
     */
    public XmlSignatureProductionPlaceType getSignatureProductionPlace()
    {
        return signatureProductionPlace;
    }

    /**
     * Sets the value of the signatureProductionPlace property.
     *
     * @param value
     *     allowed object is
     *     {@link XmlSignatureProductionPlaceType }
     *
     */
    public void setSignatureProductionPlace(
            XmlSignatureProductionPlaceType value)
    {
        this.signatureProductionPlace = value;
    }

    /**
     * Gets the value of the signerRole property.
     *
     * @return
     *     possible object is
     *     {@link XmlSignerRoleType }
     *
     */
    public XmlSignerRoleType getSignerRole()
    {
        return signerRole;
    }

    /**
     * Sets the value of the signerRole property.
     *
     * @param value
     *     allowed object is
     *     {@link XmlSignerRoleType }
     *
     */
    public void setSignerRole(XmlSignerRoleType value)
    {
        this.signerRole = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId()
    {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value)
    {
        this.id = value;
    }
}
