//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.09 at 09:56:29 PM BST 
//


package xades4j.xml.bind;

import jakarta.xml.bind.annotation.adapters.XmlAdapter;

import java.util.Base64;

public class Base64XmlAdapter
    extends XmlAdapter<String, byte[]>
{


    @Override
    public byte[] unmarshal(String value) {
        return Base64.getMimeDecoder().decode(value);
    }

    @Override
    public String marshal(byte[] value) {

        return Base64.getMimeEncoder().encodeToString(value);

    }

}
